name: Release npm Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
        
      - name: Install Dependencies
        run: npm ci

      - name: Build Package
        run: npm run build

      - name: Set npm Auth Token
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Create npm Release
        run: npm publish --access public
